### ISSUE TITLE
Feature request: database slicing and splicing

### ISSUE THREAD

**Issue by WilliamHPNielsen** [QCoDeS/Qcodes#1217]
Our API should expose a function/method to extract a subset of runs from a database and dump those into a new database. Similarly, injecting runs into an existing database ought to be possible. 

@johnhornibrook @QCoDeS/core

**Comment by nataliejpg** [comment]
I see two obvious scenarios:
- we run out of space and want to split the database so that the most recent experiments stay on the experiment pc and the older ones stay in another database
- we want to do the data analysis on a different pc and want to copy either a number or runs or a whole experiment. I imagine that tbh people would probably prefer something other than sql for this so it would be great to have the option to export to other formats (for single datasets or a whole experiment) but I leave that design decision to those with stronger views. If the decision is 'they should use the sql backend on their pc as well' then nevertheless the capability to grab stuff from the measurement pc and copy it into your own database easily and some examples would be fab.
