### ISSUE TITLE
Plot_dataset for partially completed 2D

### ISSUE THREAD

**Issue by ThorvaldLarsen** [QCoDeS/Qcodes#2995]
In one of the latest updates the plotting functions doesnt handle partially completed 2D dataset. It now falls back to a scatter plot instead of a partially filled map.
Ideally we would like to keep the 0.22.0 version behavior for partially completed plots.

Version 0.25.0
![image](https://user-images.githubusercontent.com/23334244/117890066-cb52f100-b2b4-11eb-9282-6aadc3af92ce.png)

Version 0.22.0
![image](https://user-images.githubusercontent.com/23334244/117890031-bc6c3e80-b2b4-11eb-8f34-0de861f3cf63.png)

**Comment by jenshnielsen** [comment]
This is caused by the dataset now being plotted from the cache which uses nan as a filler for the empty elements rather than simply omitting them. Adding something like `dataarray = dataarray[~np.isnan(dataarray)]` to `flatten_1D_data_for_plot` seems to fix this but it is unclear if this will have problematic issues for datasets that really contain nans

**Comment by jenshnielsen** [comment]
A better solution would therefor be to make use of the actual shape data if available
