### ISSUE TITLE
positioning of plotting windows

### ISSUE THREAD

**Issue by eendebakpt** [QCoDeS/Qcodes#34]
I am trying to position the plot widows. Can we add a general setGeometry method to the BasePlot object?

 The QtPlot object has member plotQ.win which is a pyqtgraph.GraphicsWindow. I can call `plotQ.win.setGeometry` to set the position (this works), but if I look at the object I get the following error:

``` python
> plotQ.win
===== Remote process raised exception on request: =====
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pyqtgraph/multiprocess/remoteproxy.py", line 213, in handleRequest
    result = getattr(opts['obj'], opts['attr'])
AttributeError: 'GraphicsWindow' object has no attribute '_ipython_display_'

===== Local Traceback to request follows: =====
===== Remote process raised exception on request: =====
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pyqtgraph/multiprocess/remoteproxy.py", line 213, in handleRequest
    result = getattr(opts['obj'], opts['attr'])
AttributeError: 'GraphicsWindow' object has no attribute '_repr_png_'
...
```

**Comment by giulioungaretti** [comment]
@eendebakpt  looking at this again I think we can close this issue, you are seing an error because you are using ipython/jupyter!
Whenever you return an object to the ipython console, or the jupyter html notebook they will try to find a *repr*  function, and the pyqt remote proxies will happily accept any function call and proxy it to the real object which then will raise an exception and then the proxy raises another exception that has a different type than what the console/ notebook expect. 

Thas is a classic failure mode of poorly designed systems, like the remote pyqtgraph (which was just designed for speed, not interactive use).

**Comment by peendebak** [comment]
@unga In #387 there is no issue any more, so in that sense the issue can be closed. Related there are the following two issues:
- There should be a generic `.setGeometry` that is both valid for the Qt and Matplotlib style windows.
- In #387 the plotting object is a subclass of `QWidget`. This has both advantages and disadvantages and we should decide whether we want this or not.

**Comment by giulioungaretti** [comment]
@peendebak  yes, because 387 uses pyqtgraph the way it's meant to be used :D  

Possibly true that there should be .setGeometry but in matplotlib that gets tricky ( @jenshnielsen  may know a lot more about this than me though) it also gets tricky in the web world where one does not take control of the desktop behavior!

**Comment by giulioungaretti** [comment]
for pyqtgraph this can be solved like this:
https://github.com/qdev-dk/Qcodes/commit/ae32c1a848b71a7a4ccd473e00b937c7ed06bfd0 

Wether or not we want to merge this back in qcodes it's something we can decide here!

@jenshnielsen  you call the shot on this one!

**Comment by jenshnielsen** [comment]
Probably we should expose a setting from config that sets a default position. That way you can configure your measurement computer with say the notebook/python console on the left and windows always popping up to the right of that and if you don't set anything in config it will default to the current behaviour.

The tricky part is handling multi monitor in a way thats both general enough and actually useful

**Comment by jenshnielsen** [comment]
For pyqtgraph this is possible via fig_x_position and fig_y_position https://github.com/QCoDeS/Qcodes/blob/master/qcodes/plots/pyqtgraph.py#L68
