### ISSUE TITLE
DataSet .complete and .fraction_complete do not work

### ISSUE THREAD

**Issue by peendebak** [QCoDeS/Qcodes#389]
A minimal example is included below. The `DataSet.complete` returns while the loop is still running.
```
import time
import numpy as np
import qcodes
from qcodes.tests.data_mocks import DataSet2D
from qcodes.tests.instrument_mocks import DummyInstrument

dataset = DataSet2D()
A = DummyInstrument(server_name='test')
sweepvalues=A.dac2[0:100:.05]

#%%
#%Loop in background
data=qcodes.Loop(sweepvalues, progress_interval=.2, delay=.001).each(A.dac1).run(background=True)
print('sync %s' % data.sync())
print('fraction %.3f' % data.fraction_complete())
data.complete() # should wait on data to be ready

for ii in range(20):    
    data.sync()
    print('sync %s' % data.sync())
    print('fraction %.3f' % data.fraction_complete())
    time.sleep(0.2)
``` 

@giulioungaretti @alexcjohnson

**Comment by alexcjohnson** [comment]
Yeah, this is a confusing situation... you need to explicitly enable the `DataManager` too, then it works:
```
data=qcodes.Loop(sweepvalues, progress_interval=.2, delay=.001).each(A.dac1).run(
    background=True, data_manager=True)
```

Without the DataManager there's no way for the background process to sync data back to the main process.

I suppose we could change the `run` flags so you only need one of them to enable multiprocessing. I wrote it this way because there *are* reasons you might want background and no data manager or vice versa, though they're kind of edge cases. So perhaps a better way, if you're going to be running this way most of the time while the new architecture is still being developed, would be to set `config.core.legacy_mp = True` which turns them both on by default.

One thing we could do is throw a warning if you use `background=True` without `data_manager=True`. That would help any `legacy_mp` users to get to the right settings.
